### ISSUE TITLE
psfStarChooser: some points not selectable

### ISSUE THREAD

**Issue by Mikea1985** [fraserw/trippy#15]
Sometimes there will be a blue points in the psfStarChooser window that cannot be selected (when clicking on it); often this seems to be because they are close to another point and you just have to zoom in to select the point, but occasionally there is a point that just cannot be selected no mater how far in I zoom. This of course means that I have no idea whether that source is a good psf source and also means that I cannot reject it (unless I can manipulate the zoom area to not include it). 

Now that I've experienced this on two machines and seen Rosemary experience it too, I'm confident that it's not just a local issue for me. I have no idea what could be causing this, so as such I also don't really have any ideas for trying to fix it. It would be nice if it is fixable, but I don't think it's super urgent, as it'll only have a minor bug (at least when there are plenty of other good sources) influencing a minority of images.

**Comment by fraserw** [comment]
To note that it won't matter because medians, assuming you have at least 10
sources. But the issue is distance and selection. How does one define a
distance metric when one axis is pixels and the other is a residual? So I
use a ranking metric to determine which is closest. But that can break, as
you've seen. I just haven't figured it out (and not spared too many brain
cells if I'm honest).

I'll try and sort this out while at the beach.

**Comment by Mikea1985** [comment]
At the beach? :-O Enjoy. 
Yeah, it makes sense that it sometimes gets confused about which point is closest, but I feel like it should be pretty obvious when I have zoomed in so far that there is only one point inside the display :-P

**Comment by fraserw** [comment]
That's only when thinking in distances. Sadly ranks are zoom agnostic. Will
think.

**Comment by Mikea1985** [comment]
Pull Request #18 addresses this issue, so I'll go ahead and close this issue.
